### ISSUE TITLE
error in the evaluation function

### ISSUE THREAD

**Issue by ramartya** [pravarmahajan/cnn-encoder-nmt#2]
Hi,

 I was trying to run the notebook, but I got stuck with this error. Please help, I would be really grateful

Traceback (most recent call last):

  File "<ipython-input-12-ae7598b10eb4>", line 1, in <module>
    runfile('C:/Users/MY DELL/Desktop/Course/6th sem/UGP/data/cnn encoder/cnn-encoder-nmt-master/code.py', wdir='C:/Users/MY DELL/Desktop/Course/6th sem/UGP/data/cnn encoder/cnn-encoder-nmt-master')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/MY DELL/Desktop/Course/6th sem/UGP/data/cnn encoder/cnn-encoder-nmt-master/code.py", line 465, in <module>
    evaluate((row.french, row.english), encoder_a, encoder_c, decoder, french_vocab, english_vocab)

  File "C:/Users/MY DELL/Desktop/Course/6th sem/UGP/data/cnn encoder/cnn-encoder-nmt-master/code.py", line 449, in evaluate
    **target_sent.append(target_vocab.id2word[ni])

KeyError: tensor(306)**

Thanks

**Comment by abhishekshaw21** [comment]
Change `target_sent.append(target_vocab.id2word[ni])` to `target_sent.append(target_vocab.id2word[ni.item()])`
this will work.
For details refer to https://github.com/SeanNaren/deepspeech.pytorch/issues/290
